config/routes.rb
Rails.application.routes.draw do

  resources :sessions, :only => [:new, :create, :destroy]
  resources :categories, :only => [:index, :show] do
    resources :items, :only => [:show] do
      resources :reviews
    end
  end

  resources :orders do
      resources :addresses
      resources :items, :only => [:update]
    end

  resources :users
  root 'categories#index'

end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :user
  has_many :orders
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  belongs_to :user
  has_one :order
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :items
end

app/models/item.rb
class Item < ActiveRecord::Base
  has_many :reviews
  has_many :raters, through: :reviews
  has_many :item_orders
  has_many :orders, through: :item_orders
  belongs_to :category


end

app/models/item_order.rb
class ItemOrder < ActiveRecord::Base
  belongs_to :item
  belongs_to :order
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  belongs_to :address
  belongs_to :cart
  has_many :item_orders
  has_many :items, through: :item_orders
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :rater, class_name:"User", foreign_key: "user_id"
  belongs_to :rated_item, class_name:"Item", foreign_key: "item_id"
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :addresses
  has_one :cart
  has_many :orders
  has_many :reviews
  has_many :rated_items, through: :reviews
  validates :username, :password, presence:true
  validates :username, uniqueness: true
  validate :password_has_numbers
end




   def password_has_numbers
    unless !!(self.password =~ /.*[0-9].*/)
      errors.add(:password, "needs at least one number")
    end
  end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  def index
    if logged_in?
     @addresses = current_user.addresses
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
    def current_user
    @user ||= User.find session[:user_id] if session[:user_id]
  end

  def authorize_user!
    redirect_to new_session_path unless current_user.present?
  end

  def logged_in?
    current_user != nil
  end


end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end
  def show
    @category = Category.find(params[:id])
  end
end

app/controllers/concerns/reviews_controller.rb
class  ReviewsController < ApplicationController
  def create
    @item = Item.find(params[:item_id])
    @review = Review.new(review_params)
    if logged_in?
      if @review.save
        current_user.reviews << @review
        @item.reviews << @review
        flash[:notice] = "Thanks for your review!"
        redirect_to :back
      else

       flash[:notice] = "Something went wrong with your review"
       redirect_to :back
     end


    else
       flash[:notice] = "Please log in"
       redirect_to :back
   end
end

end


 def review_params
    params.require(:review).permit(:rating, :body, :item_id)
  end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def show
    @item = Item.find(params[:id])
    @review = Review.new

  end

  def update
    @item = Item.find(params[:id])

    @order = Order.find_by(id: params[:order_id])
    @order.items << @item
    flash[:notice] = "Item added"
    redirect_to category_item_path(@item.category,@item)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
def show
  @order= Order.find(params[:id])
end

def edit
  @order = Order.find(params[:id])
  @addresses = current_user.addresses
end

def update
  @order = Order.find(params[:id])
  if @order.update(address_id: order_params)
    @order.update(shopped_now: false)
    flash[:notice] = "Your order has been shipped!"
    @order = current_user.orders.create
    redirect_to order_path(@order)
  else
    flash[:notice] = "Something went wrong with your order placement"
    redirect_to order_path(@order)
  end
end

# def create
#   @order = Order.create
#   redirect_to order_path(@order)

# end

 def order_params
    params.require(:order).permit(:address_id)
  end



end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by(username: params[:username])
      if @user && @user.authenticate(params[:password])
        session[:user_id] = @user.id
        redirect_to root_path
      else
        flash.now[:error] = "Incorrect Username or Password"
        render action: "new"
      end
  end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    if logged_in?
      @user = current_user
    else
      redirect_to new_user_path
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
        redirect_to root_path
    else
      flash[:error] = "Invalid sign up parameters"
      render action "new"
    end
  end
end


 def user_params
    params.require(:user).permit(:username, :password)
  end

app/helpers/application_helper.rb
module ApplicationHelper

      def current_user
    @user ||= User.find session[:user_id] if session[:user_id]
  end

  def authorize_user!
    redirect_to new_session_path unless current_user.present?
  end

    def logged_in?
    current_user != nil
  end

end

app/views/categories/index.html.erb
<%@categories.each do |category|%>
<ul>
<li><%=link_to category.name, category%></li>
</ul>
<%end%>

app/views/categories/show.html.erb
<%=@category.name%>

<%@category.items.each do |item|%>
<ul>
  <li><%=link_to item.name, category_item_path(@category, item)%></li>
  <li>$<%=item.price%></li>

</ul>
<%end%>

app/views/items/show.html.erb
<%=@item.name%>
Description:
<br>
<%=@item.description%>
<br>

<%=flash[:notice] if flash.any?%>

<%=link_to "Add to Cart!", order_item_path(current_user.orders.find_by(shopped_now:true), @item), :method => :put%>


 <%@item.reviews.each do |review|%>
  <ul>
    <li>Reviewed <%=review.created_at%> by <%=review.rater.username%>
      <li>Rating: <%=review.rating%>
       <li>Review: <%= review.body%>
  </ul>
  <%end%>


  <br>
  <%= form_for [@item.category, @item, @item.reviews.build] do |f| %>

<br>
  <%= f.label :rating %>:
  <%= f.select :rating, [['1','1'],['2','2'],['3','3'],['4','4'],['5','5']] %>

  <%= f.label :body %>:
  <%= f.text_field :body, :cols => "30", :rows => "10" %><br />

  <%= f.submit value= "Review" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AmazonClone</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <h1>Drewmazon</h1>
  <nav>
    <%=link_to "Home", root_path%>

    <%if logged_in?%>
    <%=link_to "Sign out", session_path(session[:user_id]), method: :delete%>
    <%=link_to current_user.username, user_path(current_user.id)%>
    <%if !!Order.find_by(shopped_now:true)%>
    <%=link_to "Cart", order_path(Order.find_by(shopped_now:true).id)%>
    <%else%>
    <%=link_to "Cart", order_path(Order.find(1).id)%>
    <%end%>

    <%else%>
    <%=link_to "Log in", new_session_path%>
    <%=link_to "Sign up", new_user_path%>
    <%end%>
  </nav>

<%= yield %>

</body>
</html>

app/views/orders/_order.html.erb
  <%= form_for [@order] do |f| %>

  <%= f.label :pick an address %>:
  <%= f.select :rating, @addresses.each {|address| print [address], [address.id]} %>

  <%= f.submit value= "Pick addreess" %>
<% end %>

app/views/orders/edit.html.erb
  <%= form_for [@order] do |f| %>

  <%= f.label :pick_address %>:
  <%= f.collection_select :address_id, @addresses, :id, :street   %>

  <%= f.submit value= "Pick address" %>
<% end %>

app/views/orders/show.html.erb
<%if @order.items.empty? || !@order.shopped_now%>
<h3> Cart is empty. Start shopping! </h3>
<%else%>
<%= flash[:notice] if !flash.empty?%>
<%@order.items.each do |item|%>
<ul>
<li>item.name</li>
<ul>
<li>$<%=item.price%></li>
</ul>
</ul>
<%end%>
<%end%>

<%=link_to "Choose Shipping Details", edit_order_path(@order) %>

app/views/users/new.html.erb
<%=flash[:error] if flash.any?%>
<%= form_for @user do |f| %>

  <%= f.label :username %>:
  <%= f.text_field :username %>
   <%= f.label :password %>:
  <%= f.password_field :password  %>
  <%= submit_tag "sign up" %>
<% end  %>

app/views/users/show.html.erb
Welcome, <%=@user.username%>

<h2>Here are your past orders</h2>

<%@user.orders.where(shopped_now:false).each do |order|%>
<ul>
<li><%=order.created_at%><li>
    <%order.items.each do |item|%>
  <ul>
    <li><%=item.name%></li>
  </ul>
  <%end%>
</ul>
<%end%>